export const factionIcons = [
	"guardian",
	"rogue",
	"seeker",
	"mystic",
	"mystic_alt",
	"survivor",
	"neutral",
	"multiclass",
	"class_guardian",
	"class_rogue",
	"class_seeker",
	"class_mystic",
	"class_survivor",
];

export const slotIcons = [
	"hand_inverted",
	"hand_x2_inverted",
	"arcane_inverted",
	"arcane_x2_inverted",
	"tarot_inverted",
	"accessory_inverted",
	"body_inverted",
	"ally_inverted",
	"head_inverted",
];

export const locationIcons = [
	"triangle",
	"square",
	"heart",
	"diamond",
	"app-moon",
	"clover",
];

export const statsIcons = [
	"skill_willpower",
	"skill_willpower_inverted",
	"skill_intellect",
	"skill_intellect_inverted",
	"skill_combat",
	"skill_combat_inverted",
	"skill_agility",
	"skill_agility_inverted",
	"skill_wild",
	"skill_wild_inverted",
	"health",
	"sanity",
];

export const arkhamSlimSpecialIcons = [
	"cardicons-parallel",
	"unique",
	"core_2026",
	"asset",
	"event",
	"skill",
];

export const tokenIcons = [
	"tablet",
	"skull",
	"cultist",
	"elder_thing",
	"elder_sign",
	"auto_fail",
	"bless",
	"curse",
	"frost",
	"moon",
	"token_sealed_outline",
];

export const signIcons = [
	"seal_e",
	"seal_d",
	"seal_c",
	"seal_b",
	"seal_a",
	"tdc_rune_a",
	"tdc_rune_b",
	"tdc_rune_c",
	"tdc_rune_d",
	"tdc_rune_e",
	"tdc_rune_f",
	"tdc_rune_g",
	"tdc_rune_h",
	"tdc_rune_i",
	"tdc_rune_j",
	"tdc_rune_k",
	"tdc_rune_l",
	"tdc_rune_m",
	"tdc_rune_n",
	"tdc_rune_o",
	"tdc_rune_p",
	"tdc_rune_q",
	"tdc_rune_r",
	"tdc_rune_s",
	"tdc_rune_t",
	"tdc_rune_u",
	"tdc_rune_v",
	"tdc_rune_w",
	"tdc_rune_x",
	"tdc_rune_y",
	"tdc_rune_z",
];

export const arkhamSlimIgnoredIcons = [
	...factionIcons,
	...tokenIcons,
	...signIcons,
	"willpower",
	"intellect",
	"combat",
	"agility",
	"wild",
];

export const arkhamCardsIgnoredIcons = [
	...locationIcons,
	"multiclass",
	"level_none",
	"level_0",
	"level_1",
	"level_2",
	"level_3",
	"level_4",
	"level_5",
	"s_frame_background",
	"s_level_null",
	"s_level_0",
	"s_level_1",
	"s_level_2",
	"s_level_3",
	"s_level_4",
	"s_level_5",
	"inverted_level_none",
	"inverted_level_0",
	"inverted_level_1",
	"inverted_level_2",
	"inverted_level_3",
	"inverted_level_4",
	"inverted_level_5",
	"ae_level_null",
	"ae_level_0",
	"ae_level_1",
	"ae_level_2",
	"ae_level_3",
	"ae_level_4",
	"ae_level_5",
	"class_guardian",
	"class_rogue",
	"class_seeker",
	"class_mystic",
	"class_survivor",
	"class_neutral",
	"swoop_arrow_left",
	"swoop_arrow_right",
	"swoop_arrow",
	"long_single_arrow",
	"long_arrow",
	"poi_side",
	"mythos_button_frame",
	"seal",
	"investigator",
	"fleur_top_right",
	"fleur_top_left",
	"fleur_bottom_right",
	"fleur_bottom_left",
];
